name: Deploy Supabase Edge Functions

on:
  push:
    paths:
      - 'supabase/functions/**'
      - 'supabase/config.toml'
      - '.github/workflows/deploy-supabase.yml'
    branches: [ main ]
  workflow_dispatch:

jobs:
  precheck:
    runs-on: ubuntu-latest
    outputs:
      ok: ${{ steps.have.outputs.ok }}
    steps:
      - id: have
        run: |
          if [ -n "${{ secrets.SUPABASE_ACCESS_TOKEN }}" ] && [ -n "${{ secrets.SUPABASE_PROJECT_REF }}" ]; then
            echo "ok=true" >> "$GITHUB_OUTPUT"
          else
            echo "ok=false" >> "$GITHUB_OUTPUT"
          fi

  deploy:
    needs: precheck
    if: ${{ needs.precheck.outputs.ok == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        # optional: feste Version
        # with: { version: '2.20.3' }
      - name: Deploy import-invoice
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
        run: |
          supabase login --token "$SUPABASE_ACCESS_TOKEN"
          # optional: schneller/robuster in CI
          # supabase functions deploy import-invoice --project-ref "$SUPABASE_PROJECT_REF" --use-api
          supabase functions deploy import-invoice --project-ref "$SUPABASE_PROJECT_REF"
