name: Deploy Supabase Edge Functions

on:
  push:
    paths:
      - 'supabase/functions/**'
      - 'supabase/config.toml'
      - '.github/workflows/deploy-supabase.yml'
    branches:
      - main
  workflow_dispatch:

jobs:
  precheck:
    runs-on: ubuntu-latest
    outputs:
      ok: ${{ steps.have.outputs.ok }}
    steps:
      - id: have
        run: |
          if [ -n "${{ secrets.SUPABASE_ACCESS_TOKEN }}" ] && [ -n "${{ secrets.SUPABASE_PROJECT_REF }}" ]; then
            echo "ok=true" >> "$GITHUB_OUTPUT"
          else
            echo "ok=false" >> "$GITHUB_OUTPUT"
          fi

  deploy:
    needs: precheck
    if: ${{ needs.precheck.outputs.ok == 'true' }}
    runs-on: ubuntu-latest

    permissions:
      contents: read

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1

      - name: Deploy import-invoice function
        run: |
          supabase login --token "$SUPABASE_ACCESS_TOKEN"
          supabase functions deploy import-invoice --project-ref "$SUPABASE_PROJECT_REF"
