name: Deploy Supabase Edge Functions

on:
  push:
    paths:
      - 'supabase/functions/**'
      - 'supabase/config.toml'
      - '.github/workflows/deploy-supabase.yml'
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ secrets.SUPABASE_ACCESS_TOKEN != '' && secrets.SUPABASE_PROJECT_REF != '' }}
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1

      - name: Deploy import-invoice function
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
        run: |
          supabase login --token "$SUPABASE_ACCESS_TOKEN"
          supabase functions deploy import-invoice --project-ref "$SUPABASE_PROJECT_REF"
        working-directory: supabase
